### ISSUE TITLE
Lowering build plate

### ISSUE THREAD

**Issue by johnantoni** [markwal/OctoPrint-GPX#29]
Hi,

Any ideas how to lower the build plate X & Y axis commands work fine but can't get Z axis to work only to goto home.

Sending via terminal:

    Send: G91
    Recv: ok
    Send: G1 Z-10.0000 F200
    Recv: ok

**Comment by markwal** [comment]
Huh.  It works fine for me.  Though I set my buttons to be inverted because I think of moving the build plate up and down rather than the nozzle up and down.

Perhaps your Z was already at the top and -10 means move even higher?   Z+ is plate down.  Z- is plate up because Z is supposed to be the distance between the nozzle and the plate (after homing and setting the coordinate system offsets).

**Comment by markwal** [comment]
Any luck figuring out what is distinct about your set up?
