### ISSUE TITLE
Upload/Print stall & heated bed not heating bugs?

### ISSUE THREAD

**Issue by tonyphoang-zz** [markwal/OctoPrint-GPX#5]
I noticed two bugs that I've come across.
1. When I load the .gcode file to Octoprint and press Upload/Print, the system will stall. But if I load the .gcode file, press Upload, select Hot End temperature, then finally press the Print button it will print just fine.
2. Using Makerbot to export the .gcode file, I noticed that if I select heated bed, the printer will not heat the bed.

**Comment by markwal** [comment]
The GPX plugin defaults to reprap flavor gcode which Makerware can't produce.  You need to switch it to MakerBot in settings.  That is probably why the heatbed thing happens because MakerWare sends M109 to set the heatbed temp. Though to be honest I haven't tried printing anything from Makerware.  I'll attempt something tomorrow and see if I can reproduce your issue.  It'd be helpful for you to upload a sample gcode that shows your issue (the smaller the better) somewhere (Google Drive, DropBox, etc.) and put a link to it here.

**Comment by tonyphoang-zz** [comment]
When I change it to Makerbot for gcode flavor, the load/print works but the heated bed still does not work.  Also live hot end reading is disabled during heating using this method.

In the old method - the method listed on post #1, it would show me live hot end readings. 

What would you recommend for slicing? I've been reading there's cura integration but have never used cura before.

**Comment by markwal** [comment]
Strange. On MakerBot for gcode flavor I get hotend and heat bed readings and they both heat.  It would be helpful for you to attach some gcode so I can look.

I almost always use slic3r on my pc.  It even has octoprint integration so I can upload with a button in slic3r.

I have MakerWare, RepG, Cura and Slic3r all installed and working though.

**Comment by tonyphoang-zz** [comment]
![screen shot 2015-06-09 at 6 15 46 pm](https://cloud.githubusercontent.com/assets/12704968/8070957/a7bb9458-0ed3-11e5-8ba4-c76e82a01ea6.png)

**Comment by tonyphoang-zz** [comment]
Which .log file would you like to see?

Right now I have my machine type set to replicator 2 (default)

I wonder since my printer is a ctc 3d printer which uses sailfish that it won't work.

**Comment by markwal** [comment]
Aha.  That's it.  You want to set it to replicator 1 dual.  It's a normal confusion, all of the makerbot clones are basically replicator 1 clones, but people get confused because most have gone to metal bodies, but the guts are all rep 1 flavor.

I meant the .gcode source that you were uploading not so much a log.

**Comment by tonyphoang-zz** [comment]
![pi_camera_mount_cover_no gcode](https://cloud.githubusercontent.com/assets/12704968/8072547/5b80a09e-0ee5-11e5-9a7d-f777870d9b7a.png)

Download this image to your desktop, change ending to .gcode

You were correct that I selected the wrong machine type. Now it displays hot end and bed temperatures correct. The extruder seems to slam against a wall when I initialize a load/print then seems to work fine. Any clue as to why it does that?

**Comment by tonyphoang-zz** [comment]
![screen shot 2015-06-09 at 8 26 47 pm](https://cloud.githubusercontent.com/assets/12704968/8072580/e0d709ae-0ee5-11e5-8cb4-afafecee79d8.png)

The slamming against the wall could be attributed to this?

**Comment by tonyphoang-zz** [comment]
![screen shot 2015-06-09 at 8 35 37 pm](https://cloud.githubusercontent.com/assets/12704968/8072679/34776eae-0ee7-11e5-98bb-35059b4d6f53.png)

**Comment by tonyphoang-zz** [comment]
Update: It appears to only slam against the wall when it initially starts the first print. Additional prints do not cause this issue.

**Comment by markwal** [comment]
The position on the gcode viewer is because the OctoPrint default is origin in the lower left.  There's a checkbox to have it be in the center makerbot style.  It's on the printer profile settings page.

My guess on the slam is that gpx is confused about where your print head is when it is computing the first move.  Perhaps jogging with the control panel causes this confusion since it uses relative mode.  Any difference if you haven't jogged and/or you've homed before starting to print?

**Comment by markwal** [comment]
Hmmm...  your first move is to home x and y so that doesn't seem to explain it.  I'm not sure what is going on there.  But since you say first print perhaps it is any print after jogging?  You should turn on serial.log in OctoPrint settings so you'll have one if it happens again.

**Comment by tonyphoang-zz** [comment]
I'll give that a try after my current print job is done. Also checking the center view port/reloading on model in the gcode viewer does nothing
![screen shot 2015-06-09 at 8 50 11 pm](https://cloud.githubusercontent.com/assets/12704968/8072786/23a78288-0ee9-11e5-9e8b-f106d32ff401.png)

**Comment by markwal** [comment]
No not that center. That just puts the model at the center of your screen.

Settings->Printer Profiles->Edit (pencil icon)->Origin choose Center from the dropdown

**Comment by tonyphoang-zz** [comment]
I changed the center and rebooted the pi. Next I tried to print a new file and it didn't slam against the wall. I think that was what was causing the slam

Now when the printer initializes for the first print, it centers itself in the center of the platform then goes to home.

**Comment by tonyphoang-zz** [comment]
It appears as if everything is working properly. 

One minor aesthetic issue is that after a print is done, the front LCD screen states: print is finished. When you load another print job, LCD does not clear so I can't see the progress of the print job of the second print. Manually pressing the M button clears the screen and shows the current stats.

**Comment by tonyphoang-zz** [comment]
Update on the slamming:

Looks like I spoke too soon, it slams the new printer head for additional prints.

**Comment by markwal** [comment]
OK, I need more information.  Which direction is it going when it slams?  At what point in the print does it do that?  Before or after the homing?  Now are you saying that it doesn't do it on the first print, but it does it on subsequent prints?  Does it only happen after you use the buttons on the control tab?

**Comment by tonyphoang-zz** [comment]
It slaps it towards the bottom when the extruder is traveling to the bottom left. It does it at the very beginning. It doesn't do it on the first print but only on prints after that. I don't press any buttons.

**Comment by markwal** [comment]
By bottom you mean toward the front of the printer?

Facing the printer: home position is back right.  It goes there (homing) and then travels to the front left and hits the front of the printer?  If so, then is it the G1 X-112 Y-73 Z150 F3300.0 (move to waiting position) of your starting gcode that hits the front?

If your printer has a 150mm deep bed and the offsets are set correctly (Y offset around 70 something in sailfish) then that move should end up a little beyond the front left corner of the bed and 150mm above it.

Also, if it is that move, it should have the same slap every time including when you print from x3g off of the sd card.

**Comment by tonyphoang-zz** [comment]
yeah botton represents towards the front of the printer.

my printer is 225x145x150

Should I set the printer's setting to 
x: 225
Y: 145 
z: 150
origin: center
![screen shot 2015-06-09 at 10 03 48 pm](https://cloud.githubusercontent.com/assets/12704968/8073474/71aced06-0ef3-11e5-80ec-d2d2681e44c5.png)

**Comment by markwal** [comment]
That won't help the slapping problem though.  It'll just draw the gcode viewer dimensions properly.

If it's that Y move that's causing the problem and it's just a tad too far for you y axis you need to convince MakerWare not to go that far.  I thought there was a way to edit your print box dimensions in MakerWare, but I can't find it now that I updated to 3.7.

145mm should be the same as a MakerBot Replicator 1 though and that move while it is 158mm from the home position should fit since your bot has space around the bed right?  There must be something we're missing here.

It is the move after it goes home and then it's on its way to the front left and the bed to the bottom when it slaps, right?

**Comment by markwal** [comment]
I think I spotted it.

**Comment by tonyphoang-zz** [comment]
Interesting thing is that when I hit home after canceling a print, it will go to the top right but will hit the wall about 2 inches from the top right and try and grind against the wall.

**Comment by markwal** [comment]
MakerWare doesn't put a switch to absolute positioning in the start gcode.  Maybe the bot is still in relative mode?  Although now that I type it I think there would be different symptoms of that.

You could put a G90 in OctoPrint's start gcode setting.

**Comment by tonyphoang-zz** [comment]
Something like this?

![screen shot 2015-06-09 at 10 19 07 pm](https://cloud.githubusercontent.com/assets/12704968/8073618/93da2ec8-0ef5-11e5-9809-00d317bf4aa3.png)

**Comment by markwal** [comment]
Home should run until it hits your end stop switch.  Maybe your endstop switch isn't in the right position or it isn't working?

What happens when you choose home axes from the LCD menu?

You can test the switch by tapping it with something on the way.  Don't pinch your fingers.

**Comment by tonyphoang-zz** [comment]
I tried shoving the extruder manually back to home when it grinds and it stopped.

**Comment by markwal** [comment]
Yes, your gcode settings look right.  I'd get rid of the M106 though.  Do you have a print cooling fan?  (Not an extruder heatsink fan, something aimed at the print bed controlled by the printer.)  If so, you should use M126.

**Comment by tonyphoang-zz** [comment]
My PLA printing cooling fan is always turned on so I don't have it electronically controlled

**Comment by markwal** [comment]
Ah. Then you can get rid of that M106 all together.  The reason I recommend that is that it is ambiguous in this context.  Reprap and OctoPrint define it as turn off PLA cooling fan.  Makerbot defines it as disable extruder heatsink fan and you don't want to do that.

**Comment by tonyphoang-zz** [comment]
Interesting that when I press cancel then home, it grinds

**Comment by tonyphoang-zz** [comment]
It turns out that on the LCD, it doesn't cancel the print job. Because while it's in that state, when I try to manually control the extruder after canceling, I can hear the stepper motors grinding (without hitting a wall)

**Comment by markwal** [comment]
I've got a repro.  Hang on.  I've got a bug here on the left over state between print jobs.

**Comment by tonyphoang-zz** [comment]
I'd be glad to test out your plugin and any other updates in the future as I am interested in remotely controlling my x3g printer

**Comment by tonyphoang-zz** [comment]
I noticed a behavior when it would try to print a second job.

It would moves to a random location (close to top right) and I can hear grinding (does not hit a wall)
then it would go to the bottom left and grind against the wall. 

I think when it tries to go home, it gets lost and does not reach the stopper.

**Comment by markwal** [comment]
I thought I had a repro, but I didn't.  My z shim had come loose enough to miss the z end stop but still wedge in a way that made the z grind but not make it home.  But I just put the shim back in place and I can do two prints in a row no problem.  :-(

**Comment by tonyphoang-zz** [comment]
Nothing is loose on mine. What printer do you have and does it run sail fish?

**Comment by markwal** [comment]
I have a FlashForge Creator Pro running Sailfish 7.7

**Comment by tonyphoang-zz** [comment]
It has to be a setting that's off then.I'll send you screen shots of all my settings tomorrow

**Comment by tonyphoang-zz** [comment]
I think the grinding issue for the second print for me is that it doesn't return to home right away. Any quick fixes you can think of? I thought the gcode specified that it needed to go to home

**Comment by markwal** [comment]
Yes, your gcode sends the carriage home at the start.  You could try sending that command in the terminal window and observe the printer.  Home X&Y: `G162 X Y F2000`
The MakerWare gcode has this for the waiting position: `G1 X-112 Y-73 Z150 F3300.0`
But you might want to just skip the Z while you’re experimenting since you’re having trouble with Y.   You might want to try a lower value for Y and see if it stops short.  Or what the hey, see if the printer can find the center:

```
G90
G1 X0 Y0 Z10
```

I added that Z10 just to make sure the bed is out of the way, but not move it all the way to the bottom like the makerware code.
The G90 means go absolute

**Comment by markwal** [comment]
In this whole thing have you only been printing with the right extruder?

**Comment by tonyphoang-zz** [comment]
correct, I've only printed with the right

**Comment by markwal** [comment]
Shoot.  That kills another theory.  There's an implicit move to switch to the other extruder.  I was thinking maybe at the beginning of the next you're getting an extruder offsets worth of grinding.  My guess at this point is that homing on Y isn't working for some reason.  Does the light on the switch board come on when you push the Y endstop?

**Comment by tonyphoang** [comment]
I tried running the in the terminal

Send: ```G1 X-112 Y-73 Z150 F3300.0```
Recv: ok
Send: M105
Recv: ok T0:22 /0 T1:23 /0 B:39 /0
Send: M105
Recv: ok T0:23 /0 T1:23 /0 B:39 /0
Send: M105
Recv: ok T0:23 /0 T1:23 /0 B:39 /0
Send: M105
Recv: ok T0:23 /0 T1:23 /0 B:39 /0
Send: M105
Recv: ok T0:23 /0 T1:23 /0 B:39 /0
Send: M105
Recv: ok T0:23 /0 T1:23 /0 B:39 /0
Send: Home X&Y: ```G162 X Y F2000```
Recv: ok
Send: M105
Recv: ok T0:22 /0 T1:23 /0 B:39 /0

**Comment by tonyphoang-zz** [comment]
Changing monitoring state from 'Offline' to 'Opening serial port'
Connected to: <GPX.gpxprinter.GpxPrinter instance at 0x14cf558>, starting monitor
Changing monitoring state from 'Opening serial port' to 'Connecting'
Recv: start
Recv: Makerbot v7.2echo: gcode to x3g translation by GPX
Recv: SD card ok
Changing monitoring state from 'Connecting' to 'Operational'
Send: M110
Send: M110
Recv: ok
Recv: ok
Send: M20
Recv: ok
Recv: Begin file list
Recv: abs20mm.x3g
Recv: 3dsetup
Recv: 3D Printer Manual.docx
Recv: PLA.x3g
Recv: PLA20MM.x3g
Recv: pi.x3g
Recv: Spulenspacer_37mm-2.x3g
Recv: Dual_Traffic_Cone.x3g
Recv: SPIRAL-04.x3g
Recv: rhino1-1.x3g
Recv: RPICase_mount-2.x3g
Recv: deleteme.x3g
Recv: End file list
Send: M105
Recv: ok T0:24 /0 T1:24 /0 B:39 /0
Send: M105
Recv: ok T0:23 /0 T1:23 /0 B:39 /0
Send: M105
Recv: ok T0:23 /0 T1:23 /0 B:39 /0
Send: M105
Recv: ok T0:24 /0 T1:23 /0 B:39 /0
Send: M105
Recv: ok T0:24 /0 T1:23 /0 B:39 /0
Send: M105
Recv: ok T0:24 /0 T1:23 /0 B:39 /0
Send: M105
Recv: ok T0:24 /0 T1:24 /0 B:39 /0
Send: M105
Recv: ok T0:23 /0 T1:23 /0 B:39 /0
Send: M105
Recv: ok T0:23 /0 T1:24 /0 B:39 /0
Send: M105
Recv: ok T0:24 /0 T1:23 /0 B:39 /0
Send: M105
Recv: ok T0:24 /0 T1:23 /0 B:39 /0
Send: M105
Recv: ok T0:23 /0 T1:23 /0 B:39 /0
Send: M105
Recv: ok T0:24 /0 T1:24 /0 B:39 /0
Send: M105
Recv: ok T0:23 /0 T1:24 /0 B:39 /0
Send: M105
Recv: ok T0:24 /0 T1:24 /0 B:39 /0
Send: M105
Recv: ok T0:24 /0 T1:24 /0 B:39 /0
Send: M105
Recv: ok T0:23 /0 T1:24 /0 B:39 /0
Send: M105
Recv: ok T0:23 /0 T1:23 /0 B:39 /0
Send: M105
Recv: ok T0:23 /0 T1:23 /0 B:39 /0
Send: G90
Recv: ok
Send: M105
Recv: ok T0:24 /0 T1:23 /0 B:39 /0
Send: M105
Recv: ok T0:24 /0 T1:23 /0 B:39 /0
Send: G1 X0 Y0 Z10
Recv: ok
Send: M105
Recv: ok T0:23 /0 T1:23 /0 B:39 /0
Send: G1 X0 Y0 Z10
Recv: ok
Send: M105
Recv: ok T0:24 /0 T1:23 /0 B:39 /0
Send: M105
Recv: ok T0:24 /0 T1:24 /0 B:39 /0
Send: M105
Recv: ok T0:23 /0 T1:24 /0 B:39 /0
Send: M105
Recv: ok T0:24 /0 T1:23 /0 B:39 /0
Send: M105
Recv: ok T0:24 /0 T1:23 /0 B:39 /0
Send: M105
Recv: ok T0:24 /0 T1:23 /0 B:39 /0

**Comment by tonyphoang-zz** [comment]
It's off center when I ran 
G90
G1 X0 Y0 Z10

**Comment by tonyphoang-zz** [comment]
Here are my settings 

![screen shot 2015-06-10 at 1 03 19 pm](https://cloud.githubusercontent.com/assets/12704968/8088680/322c1c5a-0f71-11e5-8c82-e2ca58858f6d.png)
![screen shot 2015-06-10 at 1 03 29 pm](https://cloud.githubusercontent.com/assets/12704968/8088681/34117308-0f71-11e5-9158-4ab87e0c5f37.png)
![screen shot 2015-06-10 at 1 03 39 pm](https://cloud.githubusercontent.com/assets/12704968/8088682/35b5a076-0f71-11e5-8c97-aa1228540f09.png)
![screen shot 2015-06-10 at 1 03 46 pm](https://cloud.githubusercontent.com/assets/12704968/8088685/37e2ecc8-0f71-11e5-9ba1-8a2ed3720923.png)
![screen shot 2015-06-10 at 1 03 52 pm](https://cloud.githubusercontent.com/assets/12704968/8088686/397c5204-0f71-11e5-880a-f7fb78c9f7ad.png)

**Comment by markwal** [comment]
Looks a lot like mine.  I invert the Z jog controls because it's more intuitive to think of moving the bed up and down rather than the head up and down since in our bots its the bed that moves.  I also change the jog speeds in OctoPrint's printer profile to match the home feedrates (reduce to 2500mm/min from 6000mm/min) since it is fast enough for jogging and doesn't jerk around as much.

Now that I think about it, you should probably home it in the sequence to find out if 0,0 is where you want it:

```
G90
G162 X Y F2000
G161 Z F900
M132 X Y Z
G1 X0 Y0 Z10
```

That sequence means: absolute mode, home X Y to maximum, home z to minimum, recall stored home offsets, and finally move to the center of the bed and 10mm away from it.
I'm not sure why, but it looks like the makerbot start gcode stomps on that M132 with a G92. But I'm a noob so what do I know?  So you might want to try it the way MakerBot has it too and compare:

```
G90
G162 X Y F2000
G161 Z F900
M132 X Y Z
G92 X152 Y75
G1 X0 Y0 Z10
```

Another thing to do here is to print a 20mm calibration cube directly from the sd card x3g and print one from octoprint using gcode and compare the result in terms of bed position and dimensions.  Maybe there's something off in the gpx conversion to steps.

**Comment by tonyphoang-zz** [comment]
Maybe I could run

G91
G28 X0 Y0

after the run is complete to zero the location?

**Comment by markwal** [comment]
```
G28 X Y
```

might be a good idea.  But makerware already does:

```
G1 Z155 F900
G162 X Y F2000
```

Perhaps that's the problem there?  If there's something off on the homing and it moves the stepper too far (gimpy endstop) then it'll be confused about where it is and that G92 up there sets it so it works anyway.  You could repeat that bit in the end gcode and define the position again.  I leave Z out here because you don't want to home it while something is on the platform.

```
M132 X Y
G92 X152 Y75
```

And that should  put the internal state to the same as the start of the first job.

**Comment by markwal** [comment]
You could also ask the bot/gpx where it thinks it is at various points and see if that jives with where it really is: `M114` in the terminal window reports the current position

**Comment by tonyphoang-zz** [comment]
Messing around with the gcode scripts, this script seem to be able to print the first and second print just fine. 

![screen shot 2015-06-10 at 3 43 03 pm](https://cloud.githubusercontent.com/assets/12704968/8092461/d5814d56-0f87-11e5-95c3-0a21a0907ecf.png)

**Comment by tonyphoang-zz** [comment]
Update: after 3 consecutive prints it doesn't slam against the wall. My settings above work really well

**Comment by tonyphoang-zz** [comment]
Update again: after 6 consecutive prints, it doesn't slam.

**Comment by markwal** [comment]
Nice.  That's good info to see what state that might be clearing up.

**Comment by tonyphoang-zz** [comment]
It could be a bug with the GPX that it does that. Might want to include
that into your next revision.

**Comment by tonyphoang-zz** [comment]
So I've been running into this problem. I have a camera mounted in the middle of my printer (top middle) and it points towards the print area but it also shows the opening and I wanted the opening to be blocked by the extruder when the print job was done.

My gcode scripts are
![screen shot 2015-06-11 at 9 43 41 am](https://cloud.githubusercontent.com/assets/12704968/8108437/60caf678-101e-11e5-9753-f9f8feb9258d.png)

What happens when I try to run a consecutive job is that the extruder will unload my filament.
Terminal reveals

Changing monitoring state from 'Operational' to 'Printing'
Send: N0 M110 N0_125
Recv: ok
Send: N1 G91_16
Recv: ok
Send: N2 G28 X0 Y0_16
Recv: ok
Send: N3 G90_19
Recv: ok
Send: N4 M136 (enable build progress)_104
Recv: ok
Send: N5 M73 P0_82
Recv: ok
Send: N6 G162 X Y F2000(home XY axes maximum)_7
Recv: ok
Send: N7 G161 Z F900(home Z axis minimum)_12
Recv: ok
Send: N8 G92 X0 Y0 Z-5 A0 B0 (set Z to -5)_64
Recv: ok
Send: N9 G1 Z0.0 F900(move Z to '0')_107
Recv: ok
Send: N10 G161 Z F100(home Z axis minimum)_50
Recv: ok
Send: N11 M132 X Y Z A B (Recall stored home offsets for XYZAB axis)_53
Recv: ok
Send: N12 G92 X152 Y75 Z0 A0 B0_93
Recv: ok
Send: N13 G1 X-112 Y-73 Z150 F3300.0 (move to waiting position)_98
Recv: ok
Send: N14 M105_18
Recv: ok T0:119 /0 T1:33 /0 B:62 /0
Send: N15 G130 X20 Y20 A20 B20 (Lower stepper Vrefs while heating)_89
Recv: ok
Send: N16 M109 S65 T0_40
Recv: ok
Send: N17 M134 T0_87

I don't know why it says N# followed by my command then #
Send: N1 G9116
Recv: ok
Send: N2 G28 X0 Y016
Recv: ok
Send: N3 G9019

**Comment by markwal** [comment]
The N is the line number and the trailing number is the checksum which are generated by OctoPrint while printing. 

But there is something wrong here, the checksum is supposed to be preceded by an asterisk. Without it, it's messing up the last parameter. I'm surprised it works at all.

**Comment by markwal** [comment]
Oh sorry. The asterisk is there, it's just the markdown here in github that turns it into italic delimeter _like this_.

You should surround code like that in triple backquotes.

**Comment by markwal** [comment]
To fix the filament issue you need to reset the extruder counter with G92 E0

**Comment by tonyphoang-zz** [comment]
It's strange that it would withdraw the extruder when a consecutive print occurs or when I cancel. It didn't do that previously. Any clue as to why it would do that?

**Comment by tonyphoang-zz** [comment]
Sorry for being a noob at this but I don't get why my code isn't working for a simple extruder travel. I'm trying to tell it to move in front of a camera by moving the extruder in the x direction away from home. It moves it across in the x and y direction.

![screen shot 2015-06-11 at 12 02 01 pm](https://cloud.githubusercontent.com/assets/12704968/8111787/b32cf142-1031-11e5-9a02-a557fe3aa639.png)

OR

![screen shot 2015-06-11 at 12 18 52 pm](https://cloud.githubusercontent.com/assets/12704968/8112181/34dfd40a-1034-11e5-892f-26588edd9f87.png)

Terminal of the second screenshot during boot up

```
Changing monitoring state from 'Offline' to 'Opening serial port'
Connected to: <GPX.gpxprinter.GpxPrinter instance at 0x744b80a8>, starting monitor
Changing monitoring state from 'Opening serial port' to 'Connecting'
Recv: start
Send: M110
Recv: Makerbot v7.2echo: gcode to x3g translation by GPX
Send: M110
Recv: SD init fail
Recv: ok
Changing monitoring state from 'Connecting' to 'Operational'
Send: M21
Recv: ok
Recv: ok
Recv: SD init fail
Send: G92 E0
Send: G91 G28 X0 Y0
Recv: ok
Recv: ok
Send: G91
Send: G1 X-135
Recv: ok X:14.20 Y:14.20 Z:0.00 E:0.00
Send: G90
Recv: ok
Recv: ok
Send: M105
Recv: ok T0:24 /0 T1:25 /0 B:42 /0

```

I don't get it, when I'm in terminal and I type 
G91
G1 X-135 
it moves in the x direction only

**Comment by markwal** [comment]
Yes, extruder position works like X, Y and Z.  It's an absolute position, so after a print you're at like A123.1885 and then the first of the subsequent print says move that motor to position A0.09861, GPX says OK, they want me to move the A extruder backward 123+mm backwards and so it does.  If your opening gcode has a G92 A0 B0 in it, it resets the notion of where the extruder is to 0 (without moving it, it just names the current position 0).

**Comment by markwal** [comment]
That line with two commands on it won't parse correctly: `G91 G28 X0 Y0` because GPX expects only one G value per line.  Off the top of my head I'm not sure which one wins.

Once you've gone home, you want to tell GPX where that is and then move to the position you want.  I'd go ahead and use absolute.

```
G28 X Y (no 0's G28 doesn't need values just axes)
G90
M132 X Y (recall firmware home offsets)
G92 X152 Y75 (define the current position as 152mm, 75mm right and above of center)
G1 X17
```

That should move the head to 17mm right of center, but leave it on the back wall which I gathered from your gcode was your intent?  Plus the other stuff means that GPX won't be confused about where the head actually is.

**Comment by markwal** [comment]
That response you got back from the relative move is a bit of a hack on my part which might need some rethinking.  GPX was made to do conversion on static files without communicating with the bot.  It simulates relative movement by computing an internal absolute position and telling the bot to move there.  Whenever you home the bot, GPX assumes it doesn't know where that is and it expects a G92 to define the current position before being asked to do a relative move.  My hack simulates a G92 by asking the firmware where it thinks we are.  This isn't something that is generally "done", but I figured it would basically work for the jog controls because it doesn't matter what we set them to because we're going to move relative, but it _will_ matter if we switch back to absolute mode and expect the coordinates to make sense. So it's safest to home the bot and define the position before doing anything.  Most start gcode that I've seen does this.

**Comment by tonyphoang-zz** [comment]
That's quite interesting that you've approached this hack in that way. 

`G92 X152 Y75`
How do you know where center is? Is it from the M132 command? I've never used that before. 
Do you start counting from home or from the bottom left?

Update:
I think I understand how it works - correct me if I'm wrong
`G28 X Y` goes home but the bot doesn't know it's home
`M132 X Y` tells that bot that it's home

Update:
Just checked out the wiki for G92 
`Allows programming of absolute zero point, by reseting the current position to the values specified. This would set the machine's X coordinate to 10, and the extrude coordinate to 90. No physical motion will occur.`

Doesn't that mean you are telling the bot that at it's current location it is at coordinate X152 Y75 from center with center being X0 Y0?

If that is true, how do you know that home is located at X152 Y75

**Comment by markwal** [comment]
Home is top, right, rearward corner of the bot.  It's where the carriage goes to hit the endstops.  G92 just defines the coordinates of wherever the bot is when the G92 is sent.  So, if you want the origin to be at the center of the print bed (0, 0) which is the the MakerBot default, the G92 after home should be how far away the nozzle is from the center of the bed in millimeters.  In my example 152mm to the right and 75mm behind.  Should be a little more than half the print bed size.  A little more because there is volume around the print bed on all sides.

**Comment by markwal** [comment]
On a dual, it should the position of the right extruder since that is the default nozzle (T0)

**Comment by tonyphoang-zz** [comment]
Got it, I understand now. 

These are my current settings which seems to work really nice for consecutive prints. 

![screen shot 2015-06-11 at 6 07 11 pm](https://cloud.githubusercontent.com/assets/12704968/8119600/b80462ee-1064-11e5-98ba-72194905cf24.png)

The 'after print job is cancelled' is kind of screwy as it does not do what I tell it to do.
Basically what I want is when the printer is not printing, I want the extruder to always be at the top middle blocking the camera.

**Comment by markwal** [comment]
You don't need my parentheticals they're just comments
Where does it end up?

**Comment by markwal** [comment]
You probably want to wait to disable the motors until after you're done using them.
The M84 should go at the end.

**Comment by tonyphoang-zz** [comment]
![screen shot 2015-06-12 at 5 15 00 pm](https://cloud.githubusercontent.com/assets/12704968/8140076/93d7dc08-1126-11e5-8603-65e10cccdb5f.png)

I moved the code above the M84 but it's still off.

It travels back home but I hear the steppers grinding against itself then it stops on the right wall near the top right before it hits the corner. If I were to manually push it to the corner then it travels just fine to the top center.

**Comment by markwal** [comment]
What happens when you home axes using the LCD number?

Sent from my Windows Phone

**Comment by tonyphoang-zz** [comment]
It homes it just fine when I select 'home axes' on the LCD.

Also side question: Would your GPX plugin work with RGB LEDs? My CTC printer has a mighty board with RGB pinouts and I'd like to set up indicator lights for different states that the printer is in
ex: color 1 for 'before print job starts'
color 2 for 'after print job completes' 

Update on the canceling issue:
It turned out that if you cancel on LCD and not cancel from octoprint, it causes that error.

**Comment by markwal** [comment]
I haven't tried it yet, but M420 gets converted to s3g 146 command which is Set RGB LED value:

```
M420 R0 E255 B255 P1 (R is red, E is green, B is blue, P is whether to blink or no)
```

On the hitting the edge, maybe it's the order gpx (see home_axes at or around gpx.c:1200) is deciding to do the move effects whether there's a good reading on the endstop. Do your endstops light their LEDs when you touch the switch?

**Comment by tonyphoang-zz** [comment]
My end stops do light up.

Does GPX control the rgb LEDs too?

## 

Sent from Gmail Mobile on iPhone 6 Plus

**Comment by markwal** [comment]
GPX translates that M420 to the x3g command for rgb LEDs. Haven't tried it myself yet.

**Comment by markwal** [comment]
I don't understand why your homing isn't working.  The homing from the LCD menu just runs an onboard script.  I don't know if this is helpful, but unless CTC modified your sailfish somehow the onboard home script is the equivalent of what GPX turns this into:

```
M18 A ; turn off the right extruder motor
M73 P0 ; start a build
G21 ; mm units
G90 ; absolute
G162 X Y F2500 ; home XY axes max
G161 Z F1100 ; home Z axes minimum
G92 X0 Y0 Z-5 A0 B0 ; name that position (0, 0, -5, 0, 0)
G1 Z0 ; move the bed down 5mm
G161 Z F100 ; slowly move it back
```

Typing it out, maybe there's a speed problem reading that endstop while homing, perhaps if you add the feed rate to your G28: `G28 X Y F2500`

**Comment by tonyphoang-zz** [comment]
`M18 A ; turn off the right extruder motor
M73 P0 ; start a build
G21 ; mm units
G90 ; absolute
G162 X Y F2500 ; home XY axes max
G161 Z F1100 ; home Z axes minimum
G92 X0 Y0 Z-5 A0 B0 ; name that position (0, 0, -5, 0, 0)
G1 Z0 ; move the bed down 5mm
G161 Z F100 ; slowly move it back`

That code causes it to go halfway back then grind and continue moving to the right until it hits a wall. When I manually push it back to home, it works fine.

**Comment by tonyphoang-zz** [comment]
Side note: I've ordered 5 meters of RGB LEDs. Will let you know the results of the code.

Also there is another project that I'd like to do- automated part removal.
I was going to add gcode to the 'after finished' section of the gcode script that would raise the bed and move the extruder from the back to the front. I would probably put something in front of the extruder to protect it as it's moving. I do think I need to stop using blue painters tape and go with the glass in order for the part to come off easier.

**Comment by tonyphoang-zz** [comment]
I tried using your code for the RGB led but no dice.

![screen shot 2015-06-17 at 2 43 03 pm](https://cloud.githubusercontent.com/assets/12704968/8215625/30d1c1be-14ff-11e5-81cb-d12930a44a09.png)

I tried adding G90 to the front with no effect

**Comment by markwal** [comment]
Like I say.  I haven't done anything with M420.  What did you wire the LEDs to?  On another thread, I thought people were talking about LEDs wired up to the bot's motherboard like FlashForge from the factory, but people meant to the Pi directly.  If you're wiring to the pi, you need a different approach.

**Comment by markwal** [comment]
Plus for stuff like this you should use the Terminal tab for experimentation.

**Comment by tonyphoang-zz** [comment]
I wired the LEDs to the mighty board itself. There are rgb outputs there.

![2015-06-17 16 37 42](https://cloud.githubusercontent.com/assets/12704968/8218295/14482df6-1510-11e5-8986-19d19ce7efef.jpg)

**Comment by markwal** [comment]
Seems right.  And that's what the gcode is designed to control.  Do they work from RepG?

**Comment by markwal** [comment]
http://www.sailfishfirmware.com/doc/parameters-rgb-led.html#x25-650004.7

**Comment by tonyphoang-zz** [comment]
Thanks for trying to help. Turns out it was the cheap eBay 24v rgb leds
that were the issue. I used a multimeter on the rgb port and it was
registering variable voltages when I changed the color values.

**Comment by markwal** [comment]
I found out some really important/relevant info for your homing issue above.  It turns out, the s3g/x3g protocol doesn't actually know how to do set position (G92) on only selected axes.  So any G92 sets the position of all the axes even if you didn't specify.  For example,

`G92 Z0`

will get translated to

`G92 Xsomething Ysomething Z0 Asomething Bsomething`

Those "somethings" are based on where GPX thinks the bot should be at that moment, but in the plugin, it is probably wrong because it gets the position by asking the bot, and the bot answers [by design] _immediately_ rather than synced with the tail end of the communication.  I say "by design" because the query is intended for monitoring not for synchronization of host state.

I _think_ I've got this fixed in my latest checkins to master.  I haven't pushed those changes out in a release yet so to try them you have to run from source and git pull to the leading edge.  My approach is to move asking the bot where it is from its previous position in the code which is whenever it needed to know, but didn't.  And I moved it to all the places where GPX loses track instead and I attempt to wait for the bot to drain the queue first.  So on: connect, home, recall home offset and cancel, I wait for the queue to drain and then ask the bot where it is.
